#include <stdio.h>
#include <conio.h>

void main()
{
	clrscr();
	printf("                                June 12, 2017 1:45pm\n");
	printf("                                                        \n");
	printf("I want to be good at programming; So now I am practicing C++");
	printf(". It's really hard\nbecause I ignored or simply because I don't get it that much and btw It's my 3rdday to learn and I don't know why I am documenting it maybe because I'm actuallyabout to learn it. Let me change topic here and it's all about if and else. I   don't know how it works but I'm here trying to comprehend it. My problem is thatit involves math, :( therefore I should learn the very basics of how this if andelse works. It's really bad also because we don't have an internet connection right now so how can I even search and practice C++? But luckily I have some extraC++ extensions to look upon to.\n");
	printf("                                  *END* 2:13pm\n");
	getch();
}